<?php
$USERNAME = '';
$PASSWORD = '';

$SPIRA_HOST = '';
$SPIRA_USERNAME = '';
$SPIRA_PASSWORD = '';
$SPIRA_DATABASE = '';

$EMAIL_RECIPIENTS = array();
$PICKING_RECIPIENTS = array();
$PRIOS_RECIPIENTS = array();
$SMTP_HOST = '';

$SITE_URL = '';
